name: Build Flutter Windows App

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'  # o la que uses tú
        channel: 'stable'

    - name: Instalar dependencias
      run: flutter pub get

    - name: Habilitar soporte para Windows
      run: flutter config --enable-windows-desktop

    - name: Compilar para Windows
      run: flutter build windows

    - name: Crear ZIP del ejecutable
      run: Compress-Archive -Path build/windows/runner/Release/* -DestinationPath build/flutter_windows_app.zip

    - name: Subir artefacto
      uses: actions/upload-artifact@v3
      with:
        name: flutter_windows_app
        path: build/flutter_windows_app.zip
