# Nombre del Workflow (aparecerá en la pestaña Actions de GitHub)
name: Build Flutter Windows App

# ¿Cuándo se ejecuta este workflow?
on:
  # Cuando haces push a la rama 'main'
  push:
    branches: [ main ]
  # También permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

# Definición de los trabajos (jobs) a ejecutar
jobs:
  # Nombre del trabajo (puede ser cualquiera)
  build-windows:
    # Usar una máquina virtual Windows proporcionada por GitHub
    runs-on: windows-latest

    # Pasos que se ejecutarán en la máquina virtual
    steps:
      # 1. Descargar tu código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4 # Acción predefinida para descargar código

      # 2. Configurar el entorno de Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Acción popular para configurar Flutter
        with:
          channel: 'stable' # Usar el canal estable de Flutter (puedes cambiarlo)
          # flutter-version: '3.x.x' # Opcional: especificar una versión exacta

      # 3. Habilitar soporte de escritorio Windows (por si acaso)
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      # 4. Obtener las dependencias de Flutter (como flutter pub get)
      - name: Get dependencies
        run: flutter pub get

      # 5. Construir la aplicación para Windows en modo Release
      - name: Build Windows Release
        run: flutter build windows --release # Compila la versión final

      # --- PASO DE DIAGNÓSTICO CON SCRIPT POWERSHELL CORREGIDO ---
      # 6a. Verificar y Listar Salida del Build
      - name: Check Build Output
        run: |
          $outputPath = "build\windows\x64\runner\Release"
          if (Test-Path -Path $outputPath) {
            # El directorio existe, mostrar contenido (caso éxito)
            Write-Host "Build output found at $outputPath. Contents:"
            Get-ChildItem -Path $outputPath -Recurse
          } else {
            # El directorio NO existe, mostrar error y revisar padres
            Write-Error "¡ERROR! Build output directory '$outputPath' not encontrado."

            $parentPath1 = "build\windows\x64\runner"
            if (Test-Path -Path $parentPath1) {
              Write-Host "Contents of $parentPath1:"
              Get-ChildItem -Path $parentPath1
            } else {
              # Si tampoco existe runner, revisar build\windows
              $parentPath2 = "build\windows"
              if (Test-Path -Path $parentPath2) {
                Write-Host "Contents of $parentPath2:"
                Get-ChildItem -Path $parentPath2
              } else {
                Write-Host "'$parentPath1' and '$parentPath2' not found."
              }
            }
            exit 1 # Fallar el workflow porque faltaba el output
          }
        shell: powershell # Ejecutar con PowerShell

      # --- PASO DE EMPAQUETADO (Sin asterisco y con ruta corregida) ---
      # 6b. Empaquetar la carpeta Release
      - name: Package Release Build
        run: Compress-Archive -Path build\windows\x64\runner\Release -DestinationPath duelpoke_tourney_windows.zip -Force
        shell: powershell # Ejecutar con PowerShell

      # 7. Subir el artefacto (Sin cambios en la acción misma)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact # Nombre del artefacto en GitHub
          path: duelpoke_tourney_windows.zip # Ruta al archivo Zip que creamos